cask "yoke" do # GENERATED BY build-yoke-cask.sh
  version '0.2.0'
  sha256 "df3254f9b76948358a557645d208baa1266cae2b95f5d4c8f5d751d22131bd0d"

  url "https://github.com/ip7e/yoke/releases/download/v#{version}/Yoke-v#{version}.zip"
  name "Yoke"
  desc "Gamepad HUD for tiling window management"
  homepage "https://github.com/ip7e/yoke"

  depends_on macos: ">= :ventura"

  app "Yoke-v#{version}/Yoke.app"

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/Yoke.app"
  end
end
