cask "yoke" do # GENERATED BY build-yoke-cask.sh
  version '0.2.1'
  sha256 "de540c3a344ab24a4cbb77c38ea07a281fc870fd3e9d9739a151aa95e1104be7"

  url "https://github.com/ip7e/yoke/releases/download/v#{version}/Yoke-v#{version}.zip"
  name "Yoke"
  desc "Gamepad HUD for tiling window management"
  homepage "https://github.com/ip7e/yoke"

  depends_on macos: ">= :ventura"

  app "Yoke-v#{version}/Yoke.app"

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/Yoke.app"
  end
end
