cask "yoke" do # GENERATED BY build-yoke-cask.sh
  version '0.1.0'
  sha256 "1649934ce0166f88d5633688e3d1994f9d61646a33256f99730e7e5d72f2b45d"

  url "https://github.com/ip7e/yoke/releases/download/v#{version}/Yoke-v#{version}.zip"
  name "Yoke"
  desc "Gamepad HUD for tiling window management"
  homepage "https://github.com/ip7e/yoke"

  depends_on macos: ">= :ventura"

  app "Yoke-v#{version}/Yoke.app"

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/Yoke.app"
  end
end
